MODEL:
  META_ARCHITECTURE: "SemanticSegmentor"
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    FPN:
      IN_FEATURES: ["res2", "res3", "res4", "res5"]
#  SEM_SEG_HEAD:
#    NAME: "DANetHead"
#    COMMON_STRIDE: 8
#    CONVS_DIM: 64
#    IN_FEATURES: ["res5"]
#    NUM_CLASSES: 19
SOLVER:
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  IMS_PER_BATCH: 16
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
DATASETS:
  TRAIN: ("coco_2017_train_panoptic_stuffonly",)
  TEST: ("coco_2017_val_panoptic_stuffonly",)
TEST:
  EVAL_PERIOD: 30


