MODEL:
  META_ARCHITECTURE: "SemanticSegmentor"
  BACKBONE:
    NAME: "build_dilated_resnet_backbone"
  DILATED_RESNET:
    NORM: "SyncBN"
  SEM_SEG_HEAD:
    NAME: "DANetHead"
    COMMON_STRIDE: 8
    CONVS_DIM: 64
    IN_FEATURES: ["res5"]
    NUM_CLASSES: 19
SOLVER:
  BASE_LR: 0.01
  STEPS: (18000,)
  MAX_ITER: 24000
  IMS_PER_BATCH: 8
INPUT:
  MIN_SIZE_TRAIN: (800, 832, 864, 896, 928, 960)
  MAX_SIZE_TRAIN: 960
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 960
DATASETS:
  TRAIN: ("cityscapes_fine_sem_seg_train",)
  TEST: ("cityscapes_fine_sem_seg_val",)
TEST:
  EVAL_PERIOD: 30


