MODEL:
  META_ARCHITECTURE: "EMASegmentor"
  BACKBONE:
    NAME: "build_dilated_resnet_backbone"
  DILATED_RESNET:
    NORM: "SyncBN"
  SEM_SEG_HEAD:
    NAME: "EMAHead"
    NORM: "SyncBN"
DATALOADER:
  NUM_WORKERS: 16
SOLVER:
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  BASE_LR: 9e-3
  BIAS_LR_FACTOR: 2.0
  WEIGHT_DECAY_BIAS: 0.0
  MAX_ITER: 30000
  IMS_PER_BATCH: 16
TEST:
  EVAL_PERIOD: 2000


