_BASE_: "base.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-152.pkl"
  DILATED_RESNET:
    DEPTH: 152
    STRIDE: 8
  SEM_SEG_HEAD:
    NUM_CLASSES: 53
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
DATASETS:
  TRAIN: ("coco_2017_train_panoptic_stuffonly",)
  TEST: ("coco_2017_val_panoptic_stuffonly",)
OUTPUT_DIR: "./output/coco/r152"
