_BASE_: "base.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  DILATED_RESNET:
    DEPTH: 50
    STRIDE: 16
  SEM_SEG_HEAD:
    COMMON_STRIDE: 16
    NUM_CLASSES: 19
INPUT:
  MIN_SIZE_TRAIN: (800, 832, 864, 896, 928, 960, 992, 1024)
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TRAIN: 2048
  MAX_SIZE_TEST: 2048
DATASETS:
  TRAIN: ("cityscapes_fine_sem_seg_train",)
  TEST: ("cityscapes_fine_sem_seg_val",)
OUTPUT_DIR: "./output/cityscapes/r50"
