_BASE_: "base.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  DILATED_RESNET:
    DEPTH: 50
  SEM_SEG_HEAD:
    COMMON_STRIDE: 8
    NUM_CLASSES: 54
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
DATASETS:
  TRAIN: ("coco_2017_train_panoptic_stuffonly",)
  TEST: ("coco_2017_val_panoptic_stuffonly",)
OUTPUT_DIR: "./output/coco/r50"
