_BASE_: "base.yaml"
MODEL:
  WEIGHTS: "./epochs/resnet50-25c4b509.pth"
  DILATED_RESNET:
    DEPTH: 50
    STRIDE: 8
  SEM_SEG_HEAD:
    NUM_CLASSES: 54
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
DATASETS:
  TRAIN: ("coco_2017_train_panoptic_stuffonly",)
  TEST: ("coco_2017_val_panoptic_stuffonly",)
OUTPUT_DIR: "./output/coco/r50"
