from detectron2.config import CfgNode as CN


def add_danet_config(cfg):
    """
    Add config for DANet.
    """
    _C = cfg

    _C.MODEL.DILATED_RESNET = CN()

    _C.MODEL.DILATED_RESNET.DEPTH = 50
    _C.MODEL.DILATED_RESNET.OUT_FEATURES = ["res5"]
    _C.MODEL.DILATED_RESNET.NUM_GROUPS = 1
    _C.MODEL.DILATED_RESNET.NORM = "FrozenBN"
    _C.MODEL.DILATED_RESNET.WIDTH_PER_GROUP = 64
    _C.MODEL.DILATED_RESNET.STRIDE_IN_1X1 = True
    _C.MODEL.DILATED_RESNET.RES2_OUT_CHANNELS = 256
    _C.MODEL.DILATED_RESNET.STEM_OUT_CHANNELS = 64
    _C.MODEL.DILATED_RESNET.RES4_DILATION = 2
    _C.MODEL.DILATED_RESNET.RES5_DILATION = 4
